// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChMOywDRHLgf6QW3Cve-9DZPwuzBcsRC8',
    appId: '1:1073563896796:android:9391b78d50e03368181d19',
    messagingSenderId: '1073563896796',
    projectId: 'skripsi4-1fdd9',
    databaseURL: 'https://skripsi4-1fdd9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'skripsi4-1fdd9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8YTSJ_ovXpW3eVDSImAI-6jjI2ilrEGo',
    appId: '1:1073563896796:ios:6c0caed3d136c067181d19',
    messagingSenderId: '1073563896796',
    projectId: 'skripsi4-1fdd9',
    databaseURL: 'https://skripsi4-1fdd9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'skripsi4-1fdd9.appspot.com',
    iosBundleId: 'com.core.venturo',
  );
}
